create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null default '使用者',
    created_at timestamptz not null default now()
);

create table if not exists public.survey_points (
    id bigint generated by default as identity primary key,
    point_name text not null,
    point_type text not null default 'control' check (point_type in ('control', 'supplement')),
    status text not null default 'active' check (status in ('active', 'missing', 'pending')),
    section_name text,
    x numeric(14,3) not null,
    y numeric(14,3) not null,
    longitude double precision not null,
    latitude double precision not null,
    remark text,
    import_source text,
    created_by uuid references auth.users(id) on delete set null,
    updated_by uuid references auth.users(id) on delete set null,
    created_by_name text,
    updated_by_name text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists survey_points_name_idx on public.survey_points(point_name);
create index if not exists survey_points_xy_idx on public.survey_points(x, y);

create table if not exists public.map_notes (
    id bigint generated by default as identity primary key,
    emoji text not null default '⭐',
    remark text,
    x numeric(14,3) not null,
    y numeric(14,3) not null,
    longitude double precision not null,
    latitude double precision not null,
    created_by uuid references auth.users(id) on delete set null,
    updated_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.point_photos (
    id bigint generated by default as identity primary key,
    survey_point_id bigint not null references public.survey_points(id) on delete cascade,
    original_file_name text not null,
    storage_path text not null unique,
    content_type text not null,
    file_size bigint not null,
    description text,
    uploaded_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create table if not exists public.point_audit_logs (
    id bigint generated by default as identity primary key,
    survey_point_id bigint not null,
    action text not null check (action in ('create', 'update', 'delete', 'import')),
    user_id uuid,
    user_display_name text,
    source_file_name text,
    created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    insert into public.profiles(id, display_name)
    values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1), '使用者'))
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.audit_survey_point()
returns trigger language plpgsql security definer set search_path = public as $$
declare
    actor uuid;
    actor_name text;
    action_name text;
    source_name text;
    target_id bigint;
begin
    if tg_op = 'INSERT' then
        actor := coalesce(new.updated_by, new.created_by, auth.uid());
        target_id := new.id;
        action_name := case when new.import_source is null then 'create' else 'import' end;
        source_name := new.import_source;
    elsif tg_op = 'UPDATE' then
        actor := coalesce(new.updated_by, new.created_by, auth.uid());
        target_id := new.id;
        action_name := 'update';
    else
        actor := coalesce(old.updated_by, old.created_by, auth.uid());
        target_id := old.id;
        action_name := 'delete';
    end if;
    select display_name into actor_name from public.profiles where id = actor;
    insert into public.point_audit_logs(survey_point_id, action, user_id, user_display_name, source_file_name)
    values (target_id, action_name, actor, coalesce(actor_name, '使用者'), source_name);
    if tg_op = 'DELETE' then return old; end if;
    return new;
end;
$$;

create or replace function public.set_shared_record_metadata()
returns trigger language plpgsql security definer set search_path = public as $$
declare actor_name text;
begin
    new.updated_at := now();
    if new.updated_by is null then new.updated_by := auth.uid(); end if;
    if tg_op = 'INSERT' and new.created_by is null then new.created_by := auth.uid(); end if;
    select display_name into actor_name from public.profiles where id = new.updated_by;
    new.updated_by_name := coalesce(actor_name, '使用者');
    if tg_op = 'INSERT' then new.created_by_name := new.updated_by_name; end if;
    return new;
end;
$$;

drop trigger if exists survey_points_metadata on public.survey_points;
create trigger survey_points_metadata before insert or update on public.survey_points
for each row execute function public.set_shared_record_metadata();

drop trigger if exists survey_points_audit on public.survey_points;
create trigger survey_points_audit after insert or update or delete on public.survey_points
for each row execute function public.audit_survey_point();

create or replace function public.touch_map_note()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end;
$$;
drop trigger if exists map_notes_touch on public.map_notes;
create trigger map_notes_touch before update on public.map_notes
for each row execute function public.touch_map_note();

alter table public.profiles enable row level security;
alter table public.survey_points enable row level security;
alter table public.map_notes enable row level security;
alter table public.point_photos enable row level security;
alter table public.point_audit_logs enable row level security;

drop policy if exists "members read profiles" on public.profiles;
create policy "members read profiles" on public.profiles for select to authenticated using (true);
drop policy if exists "members update own profile" on public.profiles;
create policy "members update own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "members share survey points" on public.survey_points;
create policy "members share survey points" on public.survey_points for all to authenticated using (true) with check (true);
drop policy if exists "members share notes" on public.map_notes;
create policy "members share notes" on public.map_notes for all to authenticated using (true) with check (true);
drop policy if exists "members share photo metadata" on public.point_photos;
create policy "members share photo metadata" on public.point_photos for all to authenticated using (true) with check (true);
drop policy if exists "members read audit logs" on public.point_audit_logs;
create policy "members read audit logs" on public.point_audit_logs for select to authenticated using (true);

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('point-photos', 'point-photos', false, 20971520, array['image/jpeg','image/png','image/webp','image/heic','image/heif'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit;

drop policy if exists "members read point photos" on storage.objects;
create policy "members read point photos" on storage.objects for select to authenticated using (bucket_id = 'point-photos');
drop policy if exists "members upload point photos" on storage.objects;
create policy "members upload point photos" on storage.objects for insert to authenticated with check (bucket_id = 'point-photos');
drop policy if exists "members delete point photos" on storage.objects;
create policy "members delete point photos" on storage.objects for delete to authenticated using (bucket_id = 'point-photos');

alter table public.survey_points replica identity full;
alter table public.map_notes replica identity full;
do $$ begin
    alter publication supabase_realtime add table public.survey_points;
exception when duplicate_object then null;
end $$;
do $$ begin
    alter publication supabase_realtime add table public.map_notes;
exception when duplicate_object then null;
end $$;
